_Exams = {
    "fresh": {
        "sem1": {
            "Applied Mathematics I": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "General Physics-I": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "General Chemistry": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Introduction to Computing": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Communicative English Skills": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Civic and Ethical Education": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Health &Physical Education I": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Logic and Critical Thinking": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
        },
        "sem2": {
            "Applied Mathematics II": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "General Physics II": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Fundamentals of Programming": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Engineering Drawing": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Basic Writing Skills": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Health &Physical Education I": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Logic and Critical Thinking": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
            "Civic and Ethical Education": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
        }
    },
    "Engineering": {
        "SoEEC": {
            "2nd_1st": {
                "Data Structure and Algorithm": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                "Electronic Circuit": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                "Applied Mathematics III": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                "Fundamental of Electrical Engineering": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                "Principle of Economics": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
            },
            "CSE": {
                "2": {
                    "sem2": {
                        "Object Oriented Programming": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Discrete Mathematics for CSE": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Digital Logic Design": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Database Systems": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Electronic circuit II": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "System Programming": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Computer Graphics": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
                    }
                },
                "3": {
                    "sem1": {
                        "Algorithms": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Probability and Random Process": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Fund. of software Engineering": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Computer Architecture & Organization": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
                    },
                    "sem2": {
                        "Operating System": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Data Communication & Computer Networks": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to Artificial": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "SOftware Requirement Engineering": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Web Programming": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Advanced Programming": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
                    }
                },
                "4": {
                    "sem1": {
                        "Formal Language and automata Theory": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Engineering Research and Development Methodology": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Multimedia Tech.": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Software Design and Architecture": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Mobile Computing and Applications": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Signals and Systems": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to Data mining": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to NLP": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Computer System and security": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
                    },
                    "sem2": {
                        "Programming languages": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Project Management": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to Law": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Compiler Design": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Digital Signal Processing": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "VLSI Design": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Electrical Network Analysis and synthesis": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to Computer Vision": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
                    }
                },
                "5": {
                    "sem1": {
                        "Semester Project": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Seminar": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Distributed Systems": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Wireless mobile Networks": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Image Processing": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Human Computer Interaction": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to Audio & Video Production": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Advanced Network": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to Control Systems": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
                    },
                    "sem2": {
                        "B.Sc. Project": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Entrepreneurship for Engineers": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Computer Games & Animation": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Special Topics in Computer Science & Engineering": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Real time and Embedded Systems": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Software Quality & Testing": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Computer Ethics and Social Issues": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}},
                        "Introduction to Robotics and Industrial Automation": {"Mid": {"Math1101Mid_2010": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA", "Math1101Mid_2011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"}, "Final": {"final 1": "BQACAgQAAxkBAANEYiw3Bc3PE7vC-neun2rkQoXHJ6MAArQLAAIrhmBRYW0JbWsZ6SQjBA"}}
                    }
                }
            },
            "ECE": {
                "2": {
                    "sem1": [],
                    "sem2": []
                },
                "3": {
                    "sem1": [],
                    "sem2": []
                },
                "4": {
                    "sem1": [],
                    "sem2": []
                },
                "5": {
                    "sem1": [],
                    "sem2": []
                }
            },
            "EPCE": {
                "2": {
                    "sem1": [],
                    "sem2": []
                },
                "3": {
                    "sem1": [],
                    "sem2": []
                },
                "4": {
                    "sem1": [],
                    "sem2": []
                },
                "5": {
                    "sem1": [],
                    "sem2": []
                }
            }
        }
    },
    "Applied": {}
}
_Lists = {
    "Applied Mathematics I": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "General Physics-I": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "General Chemistry": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Computing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Communicative English Skills": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Civic and Ethical Education": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Health &Physical Education I": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Logic and Critical Thinking": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Applied Mathematics II": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "General Physics II": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Fundamentals of Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Engineering Drawing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Basic Writing Skills": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Data Structure and Algorithm": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Electronic Circuit": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Applied Mathematics III": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Fundamental of Electrical Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Principle of Economics": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Object Oriented Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Discrete Mathematics for CSE": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Digital Logic Design": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Database Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Electronic circuit II": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "System Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Graphics": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Algorithms": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Probability and Random Process": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Fund. of software Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Architecture & Organization": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Operating System": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Data Communication & Computer Networks": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Artificial": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "SOftware Requirement Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Web Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Advanced Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Formal Language and automata Theory": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Engineering Research and Development Methodology": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Multimedia Tech.": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Software Design and Architecture": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Mobile Computing and Applications": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Signals and Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Data mining": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to NLP": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer System and security": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Programming languages": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Project Management": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Law": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Compiler Design": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Digital Signal Processing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "VLSI Design": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Electrical Network Analysis and synthesis": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Computer Vision": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Semester Project": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Seminar": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Distributed Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Wireless mobile Networks": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Image Processing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Human Computer Interaction": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Audio & Video Production": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Advanced Network": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Control Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "B.Sc. Project": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Entrepreneurship for Engineers": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Games & Animation": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Special Topics in Computer Science & Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Real time and Embedded Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Software Quality & Testing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Ethics and Social Issues": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Robotics and Industrial Automation": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"
}
_Codes = {
    "Math1101": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Phys1101": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Chem1101": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE1101": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ENG1011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "LAR1011": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "HPEd1012": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "LAR1012": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Math1102": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Phys1102": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE1102": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "DME1102": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ENG1102": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE2101": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ECE2101": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "MATH2051": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "PCE2101": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "SOS311": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE2202": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE2206": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ECE3204": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3207": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ECE2202": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE2320": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3310": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3211": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ECE3103": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3205": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3203": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3204": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3221": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3206": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3308": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3306": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE3312": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4224": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4221": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4303": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4309": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4311": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ECE2204": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5317": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5321": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Unkown": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4202": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4302": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Unknown": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4310": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ECE3205": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "ECE5307": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "PCE3201": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE4312": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5201": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5205": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5307": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5309": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5311": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5313": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5315": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5319": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "PCE3204": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5202": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "SOSC412": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5304": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5306": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5308": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5310": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "CSE5312": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "PCE5308": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"
}
